CREATE TABLE PARAMS
(
  PARAM_ID        NUMBER                        DEFAULT 0,
  PARAM_NM        VARCHAR2(30 BYTE),
  STR_VAL         VARCHAR2(30 BYTE),
  NBR_VAL         NUMBER,
  DT_VAL          DATE,
  LAST_UPDT_DTTM  DATE                          DEFAULT SYSDATE,
  LAST_UPDT_USER  VARCHAR2(30 BYTE)             DEFAULT USER
)
TABLESPACE USERDATA
/


CREATE UNIQUE INDEX PARAMS_UK ON PARAMS
(PARAM_NM)
LOGGING
TABLESPACE USERDATA
/
SHOW ERRORS;
